server:
  port: 8080

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: reader
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/tnfreader}
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 200ms

  security:
    saml2:
      relyingparty:
        registration:
          tf-reader:
            entity-id: tf-reader-sp
            acs:
              location: "{baseUrl}/login/saml2/sso/{registrationId}"
            assertingparty:
              entity-id: saml-mock
              singlesignon:
                url: ${SAML_URL:https://samlmock.dev/idp?aud=tf-reader-sp&acs_url=http%3A%2F%2Flocalhost%3A8080%2Flogin%2Fsaml2%2Fsso%2Ftf-reader}
                binding: redirect
                sign-request: false
              verification:
                credentials:
                  - certificate-location: classpath:saml/samlmock-idp.crt

tf:
  catalogue:
    base-url: ${BASE_URL:http://localhost:8080}
  security:
    jwt:
      issuer: tf-reader
      secret: ${TF_JWT_SECRET}
      access-token-ttl: 15m
      refresh-token-ttl: 12h

tnf:
  auth:
    jwt:
      secret: ${TNF_JWT_SECRET}
      ttl: 1h

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  health:
    redis:
      enabled: false
